### ISSUE TITLE
Training File Archives Incorrectly Formatted

### ISSUE THREAD

**Issue by NZAbklepp** [anskarl/LoMRF#13]
The following archives of training files all seem to be incorrectly formatted: 

    Data/Examples/Structure_Learning/OSL_NLP/training.tar.bz2
    Data/Examples/Structure_Learning/OSLa_CAVIAR/training.tar.bz2
    Data/Examples/Weight_Learning/Activity_Recognition/training.tar.bz2

When I attempt to untar any the result is: 

    $ tar -xvjf training.tar.bz2 
      tar: Unrecognized archive format
      tar: Error exit delayed from previous errors.

Here is the result of `file`:

    $ file training.tar.bz2 
      training.tar.bz2: ASCII text

and `more`:

    $ more training.tar.bz2 
      version https://git-lfs.github.com/spec/v1
      oid sha256:a4e94c37635b116bfa8d1dfbaa91577d79823e21d942675fcbb515c48f1a0a18
      size 11157

Thanks!

**Comment by anskarl** [comment]
I have cloned the LoMRF project and the LoMRF-data git sub-module and everything is fine. All examples can be extracted. 

Did you followed the instructions [Download Example and Unit Testing Data](https://github.com/anskarl/LoMRF/blob/develop/docs/7_2_download_example_data.md) ?

**Comment by anskarl** [comment]
```file training.tar.bz2
training.tar.bz2: bzip2 compressed data, block size = 900k```

**Comment by vagmcs** [comment]
Hi @NZAbklepp,

The problem (probably) is that you haven't installed [git lfs](https://git-lfs.github.com/). In a Linux machine you can typically install it by using the package manager. Then clone LoMRF and the Data submodule and it should work fine.

**Comment by NZAbklepp** [comment]
Thanks, @vagmcs! That did the trick.
