### ISSUE TITLE
mismatched variables in libdai output?

### ISSUE THREAD

**Issue by hastyboomalert** [anskarl/LoMRF#2]
Hey, 

I tried to use mrfwriter to produce a ground libdai fg and ran into the issue that in the resulting fg, positive and negative literals of the same ground atom are treated as different libdai variables. Consider for example the mln: 
```
widget={A}
P(widget)
Q(widget)
3.14 P(x) ^ !Q(x)
6.28 !Q(x)
```    
I run: ./mrfwriter -i tmp.mln -q "Q/1" -e /dev/null -f FACTOR_GRAPH -o tmp.fg

and get 

```
# Factor graph
2

# -3.14 !P(A) v Q(A)
2
4 0 
2 2 
4
0 -3.14
#1 0.0
2 -3.14
3 -3.14

# 6.28 !Q(A)
1
2 
2 
2
0 6.28
#1 0.0
```
So now, we have the dai var x_0 for Q(A) from the first clause, x_2 for Q(A) from the second clause and x_4 for P(A). However, this factor graph does not reflect that x_2  depends on x_0. Thus, the most probable configuration of the MRF is x_0 = 1, x_2 = 0, and x_4 = 0, meaning that Q(A)'s accrding to x_0 and x_2 don't agree.

**Comment by anskarl** [comment]
Hi, 

Thanks for the issue reporting. I have updated both master and development batches, fixing the factor  graph output issue. 

I've also found that the number of non zero entries in the produced table was wrong, for example, in the theory above the number of non zero entries are three for the `-3.14 !P(A) v Q(A)` and one for the `6.28 !Q(A)`. The zeroed entries are commented out (i.e., in both tables: `#1 0.0`).

Therefore, the produced output (tmp.fg) for the same MLN theory is now:

```
# Factor graph
2

# -3.14 !P(A) v Q(A)
# number of variables:
2
# variables:
2 0
# all variables are binary:
2 2
# number of nonzero entries in the table:
3
# factor table:
0 -3.14
#1 0.0
2 -3.14
3 -3.14

# 6.28 !Q(A)
# number of variables:
1
# variables:
0
# all variables are binary:
2
# number of nonzero entries in the table:
1
# factor table:
0 6.28
#1 0.0
```

Could you please confirm that the above output is correct?

**Comment by hastyboomalert** [comment]
Thanks for the quick fix! As far as I can tell, the output looks correct. My inference code didn't complain either. I will do some experiments against first-order model counting in the next days, so if there are any other problems in the output, they should come up readily.
