### ISSUE TITLE
Couldn't connect SBT and LoMRF

### ISSUE THREAD

**Issue by ashalya86** [anskarl/LoMRF#23]
I'm struggling of connecting sbt and LoMRF.
By following this link(https://github.com/anskarl/LoMRF/blob/develop/docs/7_1_build_and_link_lomrf.md), I did all installations. At last to connect both sbt and LoMRF I edtied  LoMRF/build.sbt
addCommandAlias("build", ";headerCreate;compile;test;package")
addCommandAlias("rebuild", ";clean;build")

lazy val lomrf = Project("LoMRF", file("."))
  .enablePlugins(JavaAppPackaging, sbtdocker.DockerPlugin, AutomateHeaderPlugin)
	.settings(Test / logLevel := Level.Info)
	.settings(Compile / logLevel := Level.Error)
	.settings(libraryDependencies ++= Dependencies.Akka)
	.settings(libraryDependencies ++= Dependencies.Logging)
	.settings(libraryDependencies ++= Dependencies.Utils)
	.settings(libraryDependencies ++= Dependencies.Optimus)
	.settings(libraryDependencies ++= Dependencies.Testing)
libraryDependencies += "com.github.anskarl" %% "lomrf" % "0.7.0"
	
But if I type lomrf --help, it says lomrf is not a valid key. Is there anything I'm doing wrong

**Comment by anskarl** [comment]
lomrf is a script for the produced distribution from sbt. 

For instance, see the following in https://github.com/anskarl/LoMRF/blob/develop/docs/7_1_build_and_link_lomrf.md : 
```
After a successful compilation, the LoMRF distribution is located inside the ./target/universal/lomrf-<version>.zip file. You can extract this file and add the path/to/lomrf-<version>/bin in your PATH, in order to execute the LoMRF scripts from terminal
```
