### ISSUE TITLE
how to increase the heap size when running LoMRF?

### ISSUE THREAD

**Issue by chenhan97** [anskarl/LoMRF#24]
Hi, thank you so much for this package!

I got the following errors when I run the code on my own dataset:
> Uncaught error from thread [MRFBuilder-akka.actor.default-dispatcher-18Uncaught error from thread [MRFBuilder-akka.actor.default-dispatcher-12]: ]: Uncaught error from thread [MRFBuilder-akka.actor.default-dispatcher-8]: call site initialization exceptionUncaught error from thread [GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled forMRFBuilder-akka.actor.default-dispatcher-24 

I think that's because the number of evidence/rules is too much, so I'm wondering if there is any way to increase the heap size used by LoMRF? I searched a lot before but none of them works, either set JAVA environment or sbt config files.

**Comment by anskarl** [comment]
Hi @chenhan97 you can increase the memory by setting the environment variable `LOMRF_JVM_ARGS`. 

For example, to set it to 8GB, run in the shell the following:
```
LOMRF_JVM_ARGS="-Xmx8g" lomrf
```

In case that you are in windows, you have to set the VM_ARGS variable in `inc.env.bat` file.

**Comment by chenhan97** [comment]
> Hi @chenhan97 you can increase the memory by setting the environment variable `LOMRF_JVM_ARGS`.
> 
> For example, to set it to 8GB, run in the shell the following:
> 
> ```
> LOMRF_JVM_ARGS="-Xmx8g" lomrf
> ```
> 
> In case that you are in windows, you have to set the VM_ARGS variable in `inc.env.bat` file.

Thank you so much! That works
