### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class

### ISSUE THREAD

**Issue by rbrtjr** [anskarl/LoMRF#7]
Hello. 
I got this message while learning weight in example "Smokers":
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
at auxlib.trove.TroveConversions$ScalaIteratorIntObjectWrapper.<init>(TroveConversions.scala:389)
        at auxlib.trove.TroveConversions$.asScalaIteratorIntObj(TroveConversions.scala:358)
(etc...)
lp_solve installed, path configured. What's missing?
THanks

**Comment by anskarl** [comment]
Hello,

I re-run the example and I haven't noticed any issue. Please note that Max-margin weight learning requires Gurobi solver to be installed. Thereafter, for MAP inference you can use either Gurobi, lp_solve or ojalgo. For details see [Batch Max-Margin Learning](https://github.com/anskarl/LoMRF/blob/master/docs/3_weight_learning.md#batch-max-margin-learning) and [Build and Link LoMRF](https://github.com/anskarl/LoMRF/blob/master/docs/6_1_build_and_link_lomrf.md).

**Comment by rbrtjr** [comment]
Hello! Thanks! 
Yes. I dont have Gurobi but I have lp_solve. But It looks like a "scala" problem to me. 
Does CDA and ADAGRAD need Gurobi too? I tried
"lomrf wlearn -alg ADAGRAD -i smoking.mln -t smoking-train.db -o smoking-learned.mln -ne Smokes/1,Cancer/1 -lossAugmented"
and
"lomrf wlearn -alg CDA -i smoking.mln -t smoking-train.db -o smoking-learned.mln -ne Smokes/1,Cancer/1 -lossAugmented"

...
...
Model lpSolve: 0x16
Configuring variable bounds...
Adding objective function...
Creating constraints: Added 0 constraints in 0ms
Solving...
Solution status is Optimal
[INFO ] Solver time:  = 0h 0m 0s 10ms
[INFO ]
=========================== Solution ===========================
Are constraints satisfied: true
Solution status: Optimal
Objective = 10.0
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
        at auxlib.trove.TroveConversions$ScalaIteratorIntObjectWrapper.<init>(TroveConversions.scala:389)
        at auxlib.trove.TroveConversions$.asScalaIteratorIntObj(TroveConversions.scala:358)
        at lomrf.mln.inference.ILP.infer(ILP.scala:264)
...
...
Thanks again

**Comment by rbrtjr** [comment]
oops I closed the comment (reopened)

**Comment by anskarl** [comment]
I seems that [auxlib](https://github.com/anskarl/auxlib) is not in the classpath.

After step 3 of [Build and Link LoMRF](https://github.com/anskarl/LoMRF/blob/master/docs/6_1_build_and_link_lomrf.md#instructions-to-build-lomrf-from-source) the resulting LoMRF distribution is in `./target/universal/lomrf-0.5.2.zip` (for version 0.5.2). What are the contents of `lib` sub-directory in `lomrf-0.5.2.zip`? 

The correct list of files should be the following (with gurobi support):
```
ch.qos.logback.logback-classic-1.1.7.jar
ch.qos.logback.logback-core-1.1.7.jar
com.datumbox.lpsolve-5.5.2.0.jar
com.github.anskarl.auxlib-log_2.11-0.2.0.jar
com.github.anskarl.auxlib-opt_2.11-0.2.0.jar
com.github.anskarl.auxlib-trove_2.11-0.2.0.jar
com.github.anskarl.auxlib_2.11-0.2.0.jar
com.github.anskarl.lomrf-0.5.2.jar
com.github.vagmcs.optimus-solver-gurobi_2.11-2.0.0.jar
com.github.vagmcs.optimus-solver-lp_2.11-2.0.0.jar
com.github.vagmcs.optimus-solver-oj_2.11-2.0.0.jar
com.github.vagmcs.optimus_2.11-2.0.0.jar
com.google.protobuf.protobuf-java-2.5.0.jar
com.typesafe.akka.akka-actor_2.11-2.3.14.jar
com.typesafe.akka.akka-remote_2.11-2.3.14.jar
com.typesafe.akka.akka-slf4j_2.11-2.3.14.jar
com.typesafe.config-1.2.1.jar
com.vividsolutions.jts-core-1.14.0.jar
gurobi.jar
io.netty.netty-3.8.0.Final.jar
net.sf.trove4j.trove4j-3.0.3.jar
org.fusesource.jansi.jansi-1.11.jar
org.ojalgo.ojalgo-41.0.0.jar
org.scala-lang.modules.scala-parser-combinators_2.11-1.0.4.jar
org.scala-lang.modules.scala-xml_2.11-1.0.5.jar
org.scala-lang.scala-library-2.11.8.jar
org.scala-lang.scala-reflect-2.11.8.jar
org.slf4j.slf4j-api-1.7.21.jar
org.uncommons.maths.uncommons-maths-1.2.2a.jar
```

The requested class in you case is in the `com.github.anskarl.auxlib-trove_2.11-0.2.0.jar` file.

**Comment by rbrtjr** [comment]
Hello!
I think I found!
The lib folder where I extracted lomrf had two versions 2.10 and 2.11. I deleted all files 2.10 and it worked!! 
I'll continue with my experiments.
Thanks a lot!!!
